### ISSUE TITLE
Website only reading accounts from `Allow use on any chain` settings but not Polkadot

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/crowdloan-app#17]
Probably related to #7.
![Screen Shot 2021-11-04 at 2 34 40 PM](https://user-images.githubusercontent.com/40356749/140322890-843391a0-3426-43c8-8b1e-3a359e3d299a.png)

As you can see here, the website only reads accounts that are configured to be read on any chain, but it cannot read from Polkadot accounts. The page should be able to read from both any chain accounts and polkadot accounts

**Comment by elegant651** [comment]
@hoonsubin actually, it same with portal. https://github.com/PlasmNetwork/crowdloan-app/blob/main/src/config/connectApi.ts#L24  maybe investigate more, but as a quick, do you know how can I retrieve polkadot accounts?

**Comment by hoonsubin** [comment]
> @hoonsubin actually, it same with portal. https://github.com/PlasmNetwork/crowdloan-app/blob/main/src/config/connectApi.ts#L24 maybe investigate more, but as a quick, do you know how can I retrieve polkadot accounts?

I think this is the type that you're looking for https://github.com/polkadot-js/extension/blob/5c53ee7d026cb0dd056ff724064a72b316ecb091/packages/extension-inject/src/types.ts#L61
I am not sure how this is injected or how it can be filtered. I'll need to look into it too
