### ISSUE TITLE
Add/Remove on Crowdloan page

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/crowdloan-app#37]
remove
![image](https://user-images.githubusercontent.com/90048622/140951100-a4f5465e-202f-4e59-a8c5-e66396c65216.png)

'h' is missing when entering Medium site on the bottom of the page
![image](https://user-images.githubusercontent.com/90048622/140951220-44a52d9f-6d0c-44d6-9fc9-ad31f02b8d61.png)
![image](https://user-images.githubusercontent.com/90048622/140951284-8cbb093a-5748-4ee0-9e8b-14e89c85604c.png)

if u use mouse hovering on Github logo, you won't see text like others
![image](https://user-images.githubusercontent.com/90048622/140951488-282af19a-1673-48c5-8a3b-5563fba3ca30.png)

**Comment by sirius651** [comment]
Thanks for finding issue!
